#!/bin/bash
echo "Please see below for random write iops information."
grep "iops" out_random_write_bs4k_ba4k.txt  |  awk '{print $1,$4}' | cut -d "," -f 1
echo "       " 
echo "Please see below for random read iops information."
grep "iops" out_random_read_bs4k_ba4k.txt  |  awk '{print $1,$5}' | cut -d "," -f 1
echo "       " 
echo "Please see below for sequential write  throughtput information."
grep "bw=" out_sequential_write_bs1024k_ba1024k.txt |  awk '{print $1,$3}'  | cut -d "," -f 1
echo "       " 
echo "Please see below for sequential read throughput information."
grep "bw=" out_sequential_read_bs1024k_ba1024k.txt |  awk '{print $1,$4}'  | cut -d "," -f 1
echo "       "
echo "Please see below for sequential mix iops information."
r=`grep "read :" out_mix_bs4k_ba4k.txt | awk '{print $1,$5}' | cut -d "=" -f 2 | cut -d "," -f 1`
w=`grep "write:" out_mix_bs4k_ba4k.txt | awk '{print $1,$4}' | cut -d "=" -f 2 | cut -d "," -f 1`
n=`expr $r + $w`
echo "Mix iops: "$n
